#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("youreit.Resource", IsApplication=true)]

namespace youreit
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Resource.String.ApplicationName = global::youreit.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::youreit.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f090003
			public const int CurrentHotspotsDatesMockData = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int CurrentHotspotsMockData = 2131296258;
			
			// aapt resource value: 0x7f090000
			public const int MenuItemNames = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int RecentActivityMockData = 2131296257;
			
			// aapt resource value: 0x7f090005
			public const int UpcomingHotspotsDatesMockData = 2131296261;
			
			// aapt resource value: 0x7f090004
			public const int UpcomingHotspotsMockData = 2131296260;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int adSize = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int adUnitId = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int cameraBearing = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTargetLat = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraTargetLng = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int cameraTilt = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int cameraZoom = 2130771975;
			
			// aapt resource value: 0x7f010002
			public const int mapType = 2130771970;
			
			// aapt resource value: 0x7f010008
			public const int uiCompass = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiRotateGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiScrollGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiTiltGestures = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomControls = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int uiZoomGestures = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int useViewLifecycle = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int zOrderOnTop = 2130771983;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050009
			public const int common_action_bar_splitter = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int common_signin_btn_dark_text_default = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int common_signin_btn_dark_text_disabled = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_signin_btn_dark_text_focused = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int common_signin_btn_dark_text_pressed = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int common_signin_btn_default_background = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int common_signin_btn_light_text_default = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int common_signin_btn_light_text_disabled = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int common_signin_btn_light_text_focused = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int common_signin_btn_light_text_pressed = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int common_signin_btn_text_dark = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int common_signin_btn_text_light = 2131034123;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int a = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int aradius = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int b = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bar = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int basketball = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int blueSolid = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int brownSolid = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bulb = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int button = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int c = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int cafe = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int camo = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int canada = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_icon_dark = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_icon_disabled_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_icon_disabled_focus_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_icon_disabled_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_icon_focus_dark = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_icon_focus_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_icon_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_icon_normal_dark = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_icon_normal_light = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_icon_pressed_dark = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_icon_pressed_light = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_signin_btn_text_dark = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_signin_btn_text_disabled_dark = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_signin_btn_text_disabled_focus_dark = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_signin_btn_text_disabled_focus_light = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_signin_btn_text_disabled_light = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_signin_btn_text_focus_dark = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_signin_btn_text_focus_light = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_signin_btn_text_light = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_signin_btn_text_normal_dark = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_signin_btn_text_normal_light = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_signin_btn_text_pressed_dark = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_signin_btn_text_pressed_light = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int cow = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int crown = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int custom_info_bubble = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int cyborgEye = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int d = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int dice = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int dots = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int drawer_shadow_dark = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int drawer_shadow_light = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int e = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int events = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int f = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int fire = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int fireworks = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int football = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int france = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int g = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int gBlue = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int h = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int hologram = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int hotel = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int hotspot_icon_white = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int i = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int ic_drawer_light = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int ic_plusone_medium_off_client = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int ic_plusone_small_off_client = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int ic_plusone_standard_off_client = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int ic_plusone_tall_off_client = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int icecream = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int Icon = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int incloak = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int invaders = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int j = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int k = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int l = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int lightning = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int m = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int map_icon_white = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int mario = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int maroonSolid = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int Mock_Circle = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int Mock_Profile_Image = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int monoandroidsplash = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int multi = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int mushroom = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int musicnote = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int n = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int nigeria = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int night = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int o = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int orangeGradient = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int p = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int pacman = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int paw = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int pDots1 = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int pDots2 = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int penguin = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int plus = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int pokeball = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int powerup_icon_white = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int profile_icon_white = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int Profile_Image = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int pShield = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int q = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int r = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int radioactive = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int rainbowFlag = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int raven = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int record = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int resturant = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int roses = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int rubberDuck = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int s = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int sBlue = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int sGreen = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int shop = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int skittles = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int skull = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int sLightBlue = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int sLightGreen = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int sLightPink = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int sLightYellow = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int smiley = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int soccerBall = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int sOrange = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int sPeach = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int sPink = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int sPurple = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public const int sRed = 2130837629;
			
			// aapt resource value: 0x7f02007e
			public const int star = 2130837630;
			
			// aapt resource value: 0x7f02007f
			public const int sticks = 2130837631;
			
			// aapt resource value: 0x7f020080
			public const int sYellow = 2130837632;
			
			// aapt resource value: 0x7f020081
			public const int t = 2130837633;
			
			// aapt resource value: 0x7f020082
			public const int target = 2130837634;
			
			// aapt resource value: 0x7f020083
			public const int tessellate1 = 2130837635;
			
			// aapt resource value: 0x7f020084
			public const int tessellate2 = 2130837636;
			
			// aapt resource value: 0x7f020085
			public const int tourism = 2130837637;
			
			// aapt resource value: 0x7f020086
			public const int trophy = 2130837638;
			
			// aapt resource value: 0x7f020087
			public const int tShield = 2130837639;
			
			// aapt resource value: 0x7f020088
			public const int u = 2130837640;
			
			// aapt resource value: 0x7f020089
			public const int unionjack = 2130837641;
			
			// aapt resource value: 0x7f02008a
			public const int v = 2130837642;
			
			// aapt resource value: 0x7f02008b
			public const int w = 2130837643;
			
			// aapt resource value: 0x7f02008c
			public const int waves = 2130837644;
			
			// aapt resource value: 0x7f02008d
			public const int x = 2130837645;
			
			// aapt resource value: 0x7f02008e
			public const int xmen = 2130837646;
			
			// aapt resource value: 0x7f02008f
			public const int y = 2130837647;
			
			// aapt resource value: 0x7f020090
			public const int yinYang = 2130837648;
			
			// aapt resource value: 0x7f020091
			public const int z = 2130837649;
			
			// aapt resource value: 0x7f020092
			public const int zebraStripes = 2130837650;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060009
			public const int Recent_Activity_Feed = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int Recent_Activity_Title = 2131099655;
			
			// aapt resource value: 0x7f06001c
			public const int animateButton = 2131099676;
			
			// aapt resource value: 0x7f06001e
			public const int button1 = 2131099678;
			
			// aapt resource value: 0x7f06000f
			public const int button2 = 2131099663;
			
			// aapt resource value: 0x7f060025
			public const int button_Points = 2131099685;
			
			// aapt resource value: 0x7f060027
			public const int button_Tagged = 2131099687;
			
			// aapt resource value: 0x7f060026
			public const int button_Tags = 2131099686;
			
			// aapt resource value: 0x7f06000e
			public const int button_cust_buy = 2131099662;
			
			// aapt resource value: 0x7f060024
			public const int button_customize = 2131099684;
			
			// aapt resource value: 0x7f060022
			public const int button_powerup = 2131099682;
			
			// aapt resource value: 0x7f060018
			public const int content_frame = 2131099672;
			
			// aapt resource value: 0x7f06000b
			public const int customization_container1 = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int customization_container2 = 2131099661;
			
			// aapt resource value: 0x7f060011
			public const int description = 2131099665;
			
			// aapt resource value: 0x7f06001f
			public const int dismiss = 2131099679;
			
			// aapt resource value: 0x7f060017
			public const int drawer_layout = 2131099671;
			
			// aapt resource value: 0x7f060015
			public const int editText = 2131099669;
			
			// aapt resource value: 0x7f06000a
			public const int horizontalScrollView1 = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int horizontalScrollView2 = 2131099660;
			
			// aapt resource value: 0x7f060004
			public const int hybrid = 2131099652;
			
			// aapt resource value: 0x7f060013
			public const int imageView1 = 2131099667;
			
			// aapt resource value: 0x7f060016
			public const int joinGame = 2131099670;
			
			// aapt resource value: 0x7f060019
			public const int left_drawer = 2131099673;
			
			// aapt resource value: 0x7f060008
			public const int line_blue = 2131099656;
			
			// aapt resource value: 0x7f06001d
			public const int linearLayout1 = 2131099677;
			
			// aapt resource value: 0x7f060021
			public const int linearLayout2 = 2131099681;
			
			// aapt resource value: 0x7f060006
			public const int linearLayout3 = 2131099654;
			
			// aapt resource value: 0x7f060028
			public const int linearLayout4 = 2131099688;
			
			// aapt resource value: 0x7f060012
			public const int listView1 = 2131099666;
			
			// aapt resource value: 0x7f060005
			public const int map = 2131099653;
			
			// aapt resource value: 0x7f06002a
			public const int menu_map = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int menu_profile = 2131099691;
			
			// aapt resource value: 0x7f060000
			public const int none = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int normal = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int satellite = 2131099650;
			
			// aapt resource value: 0x7f060020
			public const int scrollView1 = 2131099680;
			
			// aapt resource value: 0x7f060003
			public const int terrain = 2131099651;
			
			// aapt resource value: 0x7f060014
			public const int textView = 2131099668;
			
			// aapt resource value: 0x7f060023
			public const int textView1 = 2131099683;
			
			// aapt resource value: 0x7f060010
			public const int title = 2131099664;
			
			// aapt resource value: 0x7f060029
			public const int toggleButton1 = 2131099689;
			
			// aapt resource value: 0x7f06001a
			public const int zoomInButton = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int zoomOutButton = 2131099675;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public const int google_play_services_version = 2131230720;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BasicDemo = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CustomizeScreen = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DrawerListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Feature = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int HotspotsScreen = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Login = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MapLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int MapWithOverlayLayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int MenuScreen = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Popup = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int PowerupsScreen = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int ProfileScreen = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int SettingsScreen = 2130903053;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0b0000
			public const int ActionItems = 2131427328;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int youreit = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f07001b
			public const int ApplicationName = 2131165211;
			
			// aapt resource value: 0x7f07001a
			public const int Hello = 2131165210;
			
			// aapt resource value: 0x7f070021
			public const int activity_description_axml = 2131165217;
			
			// aapt resource value: 0x7f070023
			public const int activity_description_mapwithmarkers = 2131165219;
			
			// aapt resource value: 0x7f070025
			public const int activity_description_mapwithoverlays = 2131165221;
			
			// aapt resource value: 0x7f070020
			public const int activity_label_axml = 2131165216;
			
			// aapt resource value: 0x7f070022
			public const int activity_label_mapwithmarkers = 2131165218;
			
			// aapt resource value: 0x7f070024
			public const int activity_label_mapwithoverlays = 2131165220;
			
			// aapt resource value: 0x7f07001c
			public const int app_name = 2131165212;
			
			// aapt resource value: 0x7f070015
			public const int auth_client_needs_enabling_title = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int auth_client_needs_installation_title = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int auth_client_needs_update_title = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int auth_client_play_services_err_notification_msg = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int auth_client_requested_by_msg = 2131165209;
			
			// aapt resource value: 0x7f070014
			public const int auth_client_using_bad_version_title = 2131165204;
			
			// aapt resource value: 0x7f070006
			public const int common_google_play_services_enable_button = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int common_google_play_services_enable_text = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int common_google_play_services_enable_title = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int common_google_play_services_install_button = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int common_google_play_services_install_text_phone = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int common_google_play_services_install_text_tablet = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int common_google_play_services_install_title = 2131165184;
			
			// aapt resource value: 0x7f07000c
			public const int common_google_play_services_invalid_account_text = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int common_google_play_services_invalid_account_title = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int common_google_play_services_network_error_text = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int common_google_play_services_network_error_title = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public const int common_google_play_services_unknown_issue = 2131165197;
			
			// aapt resource value: 0x7f070010
			public const int common_google_play_services_unsupported_date_text = 2131165200;
			
			// aapt resource value: 0x7f07000f
			public const int common_google_play_services_unsupported_text = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int common_google_play_services_unsupported_title = 2131165198;
			
			// aapt resource value: 0x7f070011
			public const int common_google_play_services_update_button = 2131165201;
			
			// aapt resource value: 0x7f070008
			public const int common_google_play_services_update_text = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int common_google_play_services_update_title = 2131165191;
			
			// aapt resource value: 0x7f070012
			public const int common_signin_button_text = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int common_signin_button_text_long = 2131165203;
			
			// aapt resource value: 0x7f07001d
			public const int mapsAppText = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int mapsAppTextDescription = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int streetViewText = 2131165215;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0000
			public const int Mono_Android_Theme_Splash = 2131361792;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[]
			{
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adUnitId = 1;
			
			public static int[] MapAttrs = new int[]
			{
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 6
			public const int MapAttrs_uiCompass = 6;
			
			// aapt resource value: 7
			public const int MapAttrs_uiRotateGestures = 7;
			
			// aapt resource value: 8
			public const int MapAttrs_uiScrollGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiTiltGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiZoomControls = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomGestures = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_useViewLifecycle = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_zOrderOnTop = 13;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
