#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("DemoParticle.Xamarin.Android.Resource", IsApplication=true)]

namespace DemoParticle.Xamarin.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int splash = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int splash_background = 2130837506;
			
			private Drawable()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int SplashScreen = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int AddPlayerMenuItem = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int AutomoveMenuItem = 2130968577;
			
			// aapt resource value: 0x7f040007
			public const int ChangeColorMenuItem = 2130968583;
			
			// aapt resource value: 0x7f040002
			public const int ChangeGridSizeMenuItem = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int InterestManagementMenuItem = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int RemovePlayerMenuItem = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int ShowUserInfoMenuItem = 2130968582;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
